# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobidev_proj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobidev_proj
    pod 'MediaPipeTasksVision'

  target 'mobidev_projTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mobidev_projUITests' do
    # Pods for testing
  end

end
